name: Build and deploy JAR app to Azure Web App - Docente

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Exportar secretos como variables de entorno
        run: |
            echo "SPRING_R2DBC_URL=${{ secrets.SPRING_R2DBC_URL }}" >> $GITHUB_ENV
            echo "SPRING_R2DBC_USERNAME=${{ secrets.SPRING_R2DBC_USERNAME }}" >> $GITHUB_ENV
            echo "SPRING_R2DBC_PASSWORD=${{ secrets.SPRING_R2DBC_PASSWORD }}" >> $GITHUB_ENV

      - name: Ejecutar pruebas
        run: mvn test
        env:
          SPRING_R2DBC_URL: ${{ secrets.SPRING_R2DBC_URL }}
          SPRING_R2DBC_USERNAME: ${{ secrets.SPRING_R2DBC_USERNAME }}
          SPRING_R2DBC_PASSWORD: ${{ secrets.SPRING_R2DBC_PASSWORD }}

      - name: Build with Maven
        run: mvn clean install

      - name: Verificar archivo JAR generado
        run: ls -lh target/

      - name: Subir JAR como artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/backend-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Verificar archivos descargados
        run: ls -lh

      - name: Login a Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71F2093BA55645F69066EBDA9332DE83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_014958C4218244CD84851E674E277E87 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E5F94CC8569143A19A07E2D2081AF2AF }}

      - name: Desplegar JAR a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Docente'
          slot-name: 'Production'
          package: backend-0.0.1-SNAPSHOT.jar
