name: Build and deploy JAR app to Azure Web App - Docente

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Mostrar archivos descargados
        run: ls -lh java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71F2093BA55645F69066EBDA9332DE83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_014958C4218244CD84851E674E277E87 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E5F94CC8569143A19A07E2D2081AF2AF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Docente'
          slot-name: 'Production'
          package: 'java-app/*.jar'  # ✅ patrón flexible y correcto
